name: easy_loading_button
description: A simple, easy to use, and customizable progress/loading _Material Flutter Button_ that supports variety of button styles (elevated, outlined, text).
version: 0.3.2
homepage: https://github.com/usefulteam/easy_loading_button
issue_tracker: https://github.com/usefulteam/easy_loading_button/issues

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
